---
name: release

on:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo 'Performing release'

  release:
    needs: prepare
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: ⬇️ Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/Pigalito/aws-slack-app.git
          git config --global user.email auto@email.com
          git config --global user.name auto-release

      - name: Lerna version
        run: |
          npx lerna version --create-release github --yes
