---
name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: ⬇️ Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
