---
name: release

on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo 'Performing release'

  release:
    needs: prepare
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: ⬇️ Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lerna bump version
        run: |
          npx lerna version -y --conventional-commit --create-release github
        
